#!/bin/sh
#
# this hooks makes makes the docs, and updates version number



# copy this file into the repository so that others can use it
cp .git/hooks/pre-commit git-hooks/pre-commit


# make the docs 
echo "Making the docs..."
python build/build_docs.py
python build/build_cpp_docs.py

# update version number
echo "Updating version number..."
python build/update_version.py


git add git-hooks/pre-commit
git add +xolotl/version.m
git add docs/reference/*