#!/bin/sh
#
# this hooks makes sure that all the C++ code you write or 
# modify can compile without errors this does not check 
# that the code is correct; but if you get an error here, 
# it prevents you from committing, which is a good thing 



# copy this file into the repository so that others can use it
cp .git/hooks/pre-commit git-hooks/pre-commit


# make the docs 
echo "Making the docs..."
python make_docs.py
python make_cpp_docs.py

# automatic build number
echo "Updating build number..."
git log master --pretty=oneline | wc -l > build_number

git add build_number
git add git-hooks/pre-commit
git add docs/reference/*