% this file contains preferences for xolotl
% do not edit this file. 
% if you want to specify your preferences,
% edit the pref.m file instead


%% ~~~~~~~~~~    plotting  ~~~~~~~~~~

% color voltage traces by the dominant 
% current? 
plot_color = true;

% show Calcium traces together
% with the voltage traces? 
show_Ca = true;


%% ~~~~~~~~~~  manipulate  ~~~~~~~~~~

% do you want to use approximate
% channels to speed up model interactions
% when using manipulate? 
% using approximations speeds up the integration
% and makes manipulate more responsive,
% but it can cause a seg fault
use_approx = true;


use_I_ext = true;